targets:
  $default:
    builders:
      # i18n:yamlBasedBuilder:
      #   enabled: false
      ngx_dart:
        generate_for:
           exclude:
            - "web/assets/css/**"
            - "web/assets/js/**"
            - "web/scrollbar.css"
