targets:
  $default:
    builders:
      i18n:yamlBasedBuilder:
        enabled: false
      ngdart:
        generate_for:
           exclude:
            - "web/assets/css/**"
            - "web/assets/js/**"
