targets:
  $default:
    sources:
      include:
        - $package$
        - pubspec.*
        - lib/**
        - test/**
      exclude:
        - example/**
        - build/**
        - .dart_tool/**