import 'dart:async';

import 'package:ngdart/angular.dart';

import 'sweet_alert.dart';

@Injectable()
class SweetAlertService {
  Future<SweetAlertResult<void>> show({
    String? title,
    String? message,
    String? htmlContent,
    String? footer,
    SweetAlertType type = SweetAlertType.info,
    SweetAlertPosition position = SweetAlertPosition.center,
    String confirmButtonText = 'OK',
    bool allowOutsideClick = true,
    bool allowEscapeKey = true,
    bool showCloseButton = false,
    bool backdrop = true,
    bool animation = true,
    bool reverseButtons = false,
    Duration? timer,
    bool timerProgressBar = false,
    String? width,
    String? padding,
    String? background,
    String? backgroundImageUrl,
    String? imageUrl,
    num? imageWidth,
    num? imageHeight,
    String imageAlt = '',
    SweetAlertGrowMode? grow,
    String? containerClass,
    String? popupClass,
    String? confirmButtonClass,
    SweetAlertLifecycleCallback? onOpen,
    SweetAlertLifecycleCallback? onClose,
  }) {
    return SweetAlert.show(
      title: title,
      message: message,
      htmlContent: htmlContent,
      footer: footer,
      type: type,
      position: position,
      confirmButtonText: confirmButtonText,
      allowOutsideClick: allowOutsideClick,
      allowEscapeKey: allowEscapeKey,
      showCloseButton: showCloseButton,
      backdrop: backdrop,
      animation: animation,
      reverseButtons: reverseButtons,
      timer: timer,
      timerProgressBar: timerProgressBar,
      width: width,
      padding: padding,
      background: background,
      backgroundImageUrl: backgroundImageUrl,
      imageUrl: imageUrl,
      imageWidth: imageWidth,
      imageHeight: imageHeight,
      imageAlt: imageAlt,
      grow: grow,
      containerClass: containerClass,
      popupClass: popupClass,
      confirmButtonClass: confirmButtonClass,
      onOpen: onOpen,
      onClose: onClose,
    );
  }

  Future<SweetAlertResult<bool>> confirm({
    String? title,
    String? message,
    String? htmlContent,
    String? footer,
    SweetAlertType type = SweetAlertType.question,
    SweetAlertPosition position = SweetAlertPosition.center,
    String confirmButtonText = 'OK',
    String cancelButtonText = 'Cancel',
    bool allowOutsideClick = true,
    bool allowEscapeKey = true,
    bool showCloseButton = false,
    bool backdrop = true,
    bool animation = true,
    bool reverseButtons = false,
    String? width,
    String? padding,
    String? background,
    String? backgroundImageUrl,
    String? imageUrl,
    num? imageWidth,
    num? imageHeight,
    String imageAlt = '',
    SweetAlertGrowMode? grow,
    String? containerClass,
    String? popupClass,
    String? confirmButtonClass,
    String? cancelButtonClass,
    SweetAlertLifecycleCallback? onOpen,
    SweetAlertLifecycleCallback? onClose,
  }) {
    return SweetAlert.confirm(
      title: title,
      message: message,
      htmlContent: htmlContent,
      footer: footer,
      type: type,
      position: position,
      confirmButtonText: confirmButtonText,
      cancelButtonText: cancelButtonText,
      allowOutsideClick: allowOutsideClick,
      allowEscapeKey: allowEscapeKey,
      showCloseButton: showCloseButton,
      backdrop: backdrop,
      animation: animation,
      reverseButtons: reverseButtons,
      width: width,
      padding: padding,
      background: background,
      backgroundImageUrl: backgroundImageUrl,
      imageUrl: imageUrl,
      imageWidth: imageWidth,
      imageHeight: imageHeight,
      imageAlt: imageAlt,
      grow: grow,
      containerClass: containerClass,
      popupClass: popupClass,
      confirmButtonClass: confirmButtonClass,
      cancelButtonClass: cancelButtonClass,
      onOpen: onOpen,
      onClose: onClose,
    );
  }

  Future<SweetAlertResult<String>> prompt({
    String? title,
    String? message,
    String? htmlContent,
    String? footer,
    SweetAlertType type = SweetAlertType.question,
    SweetAlertPosition position = SweetAlertPosition.center,
    SweetAlertInputType inputType = SweetAlertInputType.text,
    String? inputPlaceholder,
    String? inputValue,
    Map<String, String>? inputOptions,
    String? inputLabel,
    bool inputChecked = false,
    num? inputMin,
    num? inputMax,
    num? inputStep,
    SweetAlertInputValidator? inputValidator,
    String confirmButtonText = 'Confirm',
    String cancelButtonText = 'Cancel',
    bool allowOutsideClick = true,
    bool allowEscapeKey = true,
    bool showCloseButton = true,
    bool backdrop = true,
    bool animation = true,
    bool reverseButtons = false,
    String? width,
    String? padding,
    String? background,
    String? backgroundImageUrl,
    String? imageUrl,
    num? imageWidth,
    num? imageHeight,
    String imageAlt = '',
    SweetAlertGrowMode? grow,
    String? containerClass,
    String? popupClass,
    String? confirmButtonClass,
    String? cancelButtonClass,
    SweetAlertLifecycleCallback? onOpen,
    SweetAlertLifecycleCallback? onClose,
  }) {
    return SweetAlert.prompt(
      title: title,
      message: message,
      htmlContent: htmlContent,
      footer: footer,
      type: type,
      position: position,
      inputType: inputType,
      inputPlaceholder: inputPlaceholder,
      inputValue: inputValue,
      inputOptions: inputOptions,
      inputLabel: inputLabel,
      inputChecked: inputChecked,
      inputMin: inputMin,
      inputMax: inputMax,
      inputStep: inputStep,
      inputValidator: inputValidator,
      confirmButtonText: confirmButtonText,
      cancelButtonText: cancelButtonText,
      allowOutsideClick: allowOutsideClick,
      allowEscapeKey: allowEscapeKey,
      showCloseButton: showCloseButton,
      backdrop: backdrop,
      animation: animation,
      reverseButtons: reverseButtons,
      width: width,
      padding: padding,
      background: background,
      backgroundImageUrl: backgroundImageUrl,
      imageUrl: imageUrl,
      imageWidth: imageWidth,
      imageHeight: imageHeight,
      imageAlt: imageAlt,
      grow: grow,
      containerClass: containerClass,
      popupClass: popupClass,
      confirmButtonClass: confirmButtonClass,
      cancelButtonClass: cancelButtonClass,
      onOpen: onOpen,
      onClose: onClose,
    );
  }

  SweetAlertController toast(
    String message, {
    String? title,
    SweetAlertType type = SweetAlertType.success,
    SweetAlertPosition position = SweetAlertPosition.topEnd,
    Duration? timer = const Duration(seconds: 3),
    bool timerProgressBar = true,
    bool closeOnClick = true,
    String? containerClass,
    String? popupClass,
  }) {
    return SweetAlert.toast(
      message,
      title: title,
      type: type,
      position: position,
      timer: timer,
      timerProgressBar: timerProgressBar,
      closeOnClick: closeOnClick,
      containerClass: containerClass,
      popupClass: popupClass,
    );
  }

  void dismissAll() {
    SweetAlert.dismissAll();
  }
}
