import 'package:ngrouter/ngrouter.dart';

class DemoRoutePaths {
  static final overview = RoutePath(path: 'overview');
  static final alerts = RoutePath(path: 'alerts');
  static final progress = RoutePath(path: 'progress');
  static final accordion = RoutePath(path: 'accordion');
  static final tabs = RoutePath(path: 'tabs');
  static final modal = RoutePath(path: 'modal');
  static final offcanvas = RoutePath(path: 'offcanvas');
  static final breadcrumbs = RoutePath(path: 'breadcrumbs');
  static final pageHeader = RoutePath(path: 'page-header');
  static final pagination = RoutePath(path: 'pagination');
  static final selectionControls = RoutePath(path: 'selection-controls');
  static final select = RoutePath(path: 'select');
  static final rating = RoutePath(path: 'rating');
  static final slider = RoutePath(path: 'slider');
  static final timeline = RoutePath(path: 'timeline');
  static final typeahead = RoutePath(path: 'typeahead');
  static final wizard = RoutePath(path: 'wizard');
  static final multiSelect = RoutePath(path: 'multi-select');
  static final currency = RoutePath(path: 'currency');
  static final colorPicker = RoutePath(path: 'color-picker');
  static final datePicker = RoutePath(path: 'date-picker');
  static final timePicker = RoutePath(path: 'time-picker');
  static final dateRange = RoutePath(path: 'date-range');
  static final carousel = RoutePath(path: 'carousel');
  static final scrollSpy = RoutePath(path: 'scrollspy');
  static final tooltip = RoutePath(path: 'tooltip');
  static final popover = RoutePath(path: 'popover');
  static final nav = RoutePath(path: 'nav');
  static final dropdown = RoutePath(path: 'dropdown');
  static final datatable = RoutePath(path: 'datatable');
  static final datatableSelect = RoutePath(path: 'datatable-select');
  static final workQueue = RoutePath(path: 'work-queue');
  static final toast = RoutePath(path: 'toast');
  static final notification = RoutePath(path: 'notification');
  static final fileUpload = RoutePath(path: 'file-upload');
  static final personRegistration = RoutePath(path: 'person-registration');
  static final treeview = RoutePath(path: 'treeview');
  static final helpers = RoutePath(path: 'helpers');
  static final sweetAlert = RoutePath(path: 'sweet-alert');
  static final highlight = RoutePath(path: 'highlight');
  static final button = RoutePath(path: 'button');
  static final inputs = RoutePath(path: 'inputs');
  static final fab = RoutePath(path: 'fab');
}
